### ISSUE TITLE
Retweet dataset

### ISSUE THREAD

**Issue by HojunYou** [ant-research/EasyTemporalPointProcess#12]
In your paper and a link (https://ant-research.github.io/EasyTemporalPointProcess/user_guide/dataset.html), you mentioned "We work on a subset of 5200 most active users with an average sequence length of 70."

However, when I downloaded retweet data from your Gdrive, I found there are 20000 sequences with the average length of 108.8. Is there another retweet dataset that you used?

**Comment by iLampard** [comment]
Hi, 

indeed we have made a few versions of Retweet data and may have uploaded a different version than the one stated in the document. I will have look at it and get back to you shortly. 

Besides, we will make a new dataset api so that the data is hosted on huggingface, which is easier to visualize and avoid confusion.

**Comment by HojunYou** [comment]
Thank you for your response and the news about the dataset api!

**Comment by iLampard** [comment]
Hi, 

the dataset in Google Drive is indeed the one we used.  we will correct the information stated in the document/paper.

thanks for pointing it out.
