### ISSUE TITLE
More information about datasets

### ISSUE THREAD

**Issue by HojunYou** [ant-research/EasyTemporalPointProcess#14]
I earlier asked you about Retweet dataset information. Your answer helped me a lot.

I have some follow-up questions about the other datasets as well.
I've been trying to understand the results in details. It got me wonder what each event type means in each dataset.

For example, in Taxi dataset, the combinations of each borough (5) and actions (pick-up and drop-off) make 10 event types. But, it does not specify which event type corresponds to which integer (e.x. event type of 1 means what?) I went to data source and saw if I could get any knowledge, but I failed. 

Do you have any information on this? Not just about Taxi dataset, you used Amazon dataset and worked with the most active users and 16 event types, but I couldn't tell which event type (product category) you actually used. 

I'd greatly appreciate it if you could let me know the information, or how I can access to these information. (I tried the data sources you mentioned in your paper, but it seems like they don't have the information I'm asking)! Thanks!

**Comment by iLampard** [comment]
Hi, i found this in the old script for amazon dataset. 

The first col is event type while the second is the description text. There might be some overlap in the types (based on the meaning of the categories) because the raw data indeed has such unclear classifications.


0	Clothing
1	Shoes
2	Accessories
3	Jewelry
4	Novelty & More
5	Watches
6	Uniforms, Work & Safety
7	Luggage & Travel Gear
8	Costumes & Accessories
9	Girls
10	Boys
11	Shoe, Jewelry & Watch Accessories
12	Baby
13	Handbags & Wallets
14	Surf, Skate & Street
15	Contemporary & Designer
15	Women
15	Big & Tall
15	Men
15	Plus-Size
15	Maternity
15	Traditional & Cultural Wear
