### ISSUE TITLE
RMTPP implementation

### ISSUE THREAD

**Issue by ivan-chai** [ant-research/EasyTemporalPointProcess#23]
Hello! Thank you for contributing to the research community.

I'm now trying to train the RMTPP model and have the following questions:
1. In the original paper, if I understand it properly, there is only one scaling weight and one bias parameter for all labels, but in the EasyTPP implementation these parameters are per-label. What is the motivation behind this change and how it affects quality of the final model?
2. It seems that scaling and bias parameters are not updated during training, since they miss the nn.Paramater wrapper. Is it expected behaviour?
3. RMTPP in the original paper has the closed form solution to the likelihood computation. Is there any performance difference between the sampling-based approach from EasyTPP and the closed form estimation from the paper?

The code can be accessed via the [link](https://github.com/ant-research/EasyTemporalPointProcess/blob/main/easy_tpp/model/torch_model/torch_rmtpp.py#L27).

**Comment by iLampard** [comment]
Hi, 

1. this way is more nature to me as i think, these parameter should typically be in a vector form instead of a scalar. The effect on the results is minimal as the final result is mainly driven by whole loglike instead of the weight and bias parameters; 

2. let me check it and get back to you soon.

3. sampling-based approach is universally used for all models, for an easy comparison purpose. Compared to the closed-form formula used in the paper, there exist some difference on the loglike, but minimal impact on type/rmse prediction results (if i remember right).
