### ISSUE TITLE
How did you process the data?

### ISSUE THREAD

**Issue by Xinyu-W** [ant-research/EasyTemporalPointProcess#4]
Hello,I would like to know if you performed any time scaling on the timestamp data when processing the data? I noticed that some of the datasets have very short time intervals between events. If you did perform time scaling, what was the scaling rule and why did you choose to do so?

**Comment by iLampard** [comment]
Hi, 

All data are collected from the authors of the published papers without any further substantial processing.

Personally, I am responsible for the Taobao data processing for the HYPRO paper. For Taobao data, there is indeed some very short intervals, because the source data (from Tianchi) contains the events on the exactly the same timestamps; i simply added a very small random noise into the time intervals to avoid it. The scaling is mentioned in the paper, just to make the time unit have a common sense, i.e., one hour or half day, instead of pure unix time unit.

**Comment by Xinyu-W** [comment]
Thank you for your answer. It's very useful to me
